targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          #
          # For usage information, reference the corresponding field in
          # `JsonSerializableGenerator`.
          # any_map: false
          # checked: false
          # create_factory: true
          # create_to_json: true
          # disallow_unrecognized_keys: false
          # explicit_to_json: false
          # field_rename: snake
          # generate_to_json_function: true
          # include_if_null: true
          # nullable: true
          # use_wrappers: false
      artemis:
        options:
          schema_mapping:
            - schema: lib/github.schema.json
              output: lib/graphql/gh.dart
              queries_glob: lib/graphql/gh_*.graphql
              resolve_type_field: __typename
              add_query_prefix: true
          scalar_mapping:
            - graphql_type: URI
              dart_type: String
            - graphql_type: GitObjectID
              dart_type: String
