name: git_touch
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  rxdart: ^0.22.2
  uri: ^0.11.3
  intl: ^0.15.7
  url_launcher: ^5.0.2
  uni_links: ^0.1.4
  flutter_markdown: ^0.2.0
  shared_preferences: ^0.5.0
  nanoid: ^0.0.6
  share: ^0.6.0
  flutter_vector_icons: ^0.2.1
  github_contributions: ^0.2.0
  flutter_svg: ^0.13.0
  launch_review: ^2.0.0
  flutter_highlight: ^0.3.0
  timeago: ^2.0.18
  provider: ^3.1.0
  seti: ^0.2.0
  filesize: ^1.0.4
  tuple: ^1.0.2
  primer:
    git:
      url: git://github.com/pd4d10/primer-flutter
      path: primer

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.3
  json_serializable: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
